## Numpy

Travis Oliphant created Numpy and released it to public as Numeric in 1995 and as Numpy in 2006. 
It is written in Python and C. Now it is maintained by Python Community. 

Numpy is a powerful library that is used for numerical computing. Libraries such as Pandas and Tensorflow are build on Numpy. In Tensorflow, the output is an ndarray, which stands for n-dimensional array. 

## Arrays vs Matrices 

https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html

In Numpy, matrices are two dimensional whereas arrays can be of any dimension, i.e. n-dimensional.

In [22]:
import numpy as np   #convert image into a numpy array as oppossed to excel  # we are going to focus on arrays

In [23]:
a = np.array([])
print (type(a))

<class 'numpy.ndarray'>


## NDARRAY
An ndaray is a n-dimensional array where all items are of the same type (unlike a Python data structure) and consequently use the same amount of space. There are 21 different types of objects (also called dtypes) that can be stored in ndarray, such as
* bool_ 
* byte
* short
* int_
* single
* float_
* longfloat
* complex_
* object_
* str_

For some of the dtypes, a _ to differentiate that dtype from the corresponding Python type. Such types are also called as 'enhanced scalars).  They have the same precision as the Python type.


Creating Arrays - First let's learn about different ways of create arrays in numpy. 

In [24]:
import numpy as np

In [25]:
# declaring a simple one dimensional numpy array # how to define a n array as alitst and pass to numpy

a = [2, 6, 10] #going to treat it like a list
print(a, type(a), type(a[2]))
a = np.array(a)
print(a, type(a), a.dtype)

[2, 6, 10] <class 'list'> <class 'int'>
[ 2  6 10] <class 'numpy.ndarray'> int64


In [26]:
# declaring another simple one dimensional numpy array

a = np.array([1, 2, 3, 4])  # shorter version
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [27]:
# declaring a two dimensional numpy array

b = np.array([[1, 2, 3], [4, 5, 6]])
# note that we have to supply each row of the array as an item in a list
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [28]:
# we can create a simple ndarray by using arange
# numpy.arange(n) will create an ndarray elements starting from 0 to n-1

a = np.arange(7) # will create elements starting from 0 to 7-1
print(a)

[0 1 2 3 4 5 6]


In [29]:
# we can also include negative integers

a1 = np.arange(-7, 7)
print(a1)

[-7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6]


In [30]:
# can have step size 
a2 = np.arange(start=-10, stop=10, step=2)
print(a2)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [31]:
# Create 10 numbers between 1 and 20 including 20 - equally spaced, not random
p = np.linspace(start = 1, stop = 20, num=10)
print('The linear space of value is {0}'.format(p))

The linear space of value is [ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [32]:
"""
In-class activity - create an array using linspace that starts from -5 and stops at 5 and num = 10
"""
p = np.linspace(start = -5, stop = 5, num = 10)
print (p)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [33]:
# using zeros() method  # used for weights and biases - more like place holders / intiializer 
a = np.zeros((3, 2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
# using ones()
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [35]:
# using identity  # dlook up definition of identity, this case it creates a squaer 2 x 2
a = np.identity(2) 
print(a)

[[1. 0.]
 [0. 1.]]


In [36]:
# using empty() method 
# this will generate very small random numbers close to zero
b = np.empty((2,2)) 
print(b) 

[[1. 0.]
 [0. 1.]]


In [37]:
"""
In class activity
In the above variable b, change b[0][1] to 15 and b[1][0] to 30 and then print b. 
"""
b [0] [1] = 15
b [1] [0] = 30
print (b)


[[ 1. 15.]
 [30.  1.]]


References:

http://people.duke.edu/~ccc14/pcfb/numpympl/NumpyBasics.html

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf

http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html

http://www.labri.fr/perso/nrougier/teaching/numpy.100/

NUMPY TO MATLAB - https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html