In this notebook we will discuss statistical properties.

In [1]:
import numpy as np

In [2]:
# min() will return the minimum value 

a = np.array([[5, 7, 9], [3, -6, 11], [2, -8, 13]])
print(a)
print(np.min(a))
print(np.min(a, 0)) # along the columns (0 gives colums)
print(np.min(a, 1)) # along the rows (1 gives rows)

[[ 5  7  9]
 [ 3 -6 11]
 [ 2 -8 13]]
-8
[ 2 -8  9]
[ 5 -6 -8]


In [3]:
# max() will return the maximum value

a = np.array([[5, 7, 9], [3, 6, 11], [2, 8, 13]])
print(a)
print(np.max(a))
print(np.max(a, 0)) # along the columns
print(np.max(a, 1)) # along the rows

[[ 5  7  9]
 [ 3  6 11]
 [ 2  8 13]]
13
[ 5  8 13]
[ 9 11 13]


In [4]:
# mean() turns the mean or the average

a = np.array([[20, 10, 50], [30, 50, 70], [60, 40, 10]])
print(a)
print(np.mean(a))
print(np.mean(a, axis=0)) # along the columns
print(np.mean(a, axis=1)) # along the rows

[[20 10 50]
 [30 50 70]
 [60 40 10]]
37.77777777777778
[36.66666667 33.33333333 43.33333333]
[26.66666667 50.         36.66666667]


In [5]:
# median() returns the median median is the midpoint, not avg

a = np.array([[20, 10, 50], [30, 50, 70], [60, 40, 10]])
print(a)
print(np.median(a))
print(np.median(a, axis=0)) # along the columns
print(np.median(a, axis=1)) # along the rows

[[20 10 50]
 [30 50 70]
 [60 40 10]]
40.0
[30. 40. 50.]
[20. 50. 40.]


In [6]:
# standard deviation is the square root of average of squared deviations 
# from the mean

a = np.array([1, 2, 3, 4, 5])
print(np.mean(a))
print(np.std(a))
# this value is nothing but the square root of 2.

3.0
1.4142135623730951


In [9]:
"""
In-class activity - create an ndarray with values [2, -4, 6], [7, 4, 8] and [5, 10, 4]. 
Determine the following:
1) The maximum value
2) The minimum value
3) The mean and median values 
4) The standard deviation. 
"""
x = np.array([[2, -4, 6], [7, 4, 8], [5, 10, 4]])
print(np.mean(x))
print(np.std(x))
print(np.min(x))
print (np.max(x))
print(np.median(x))

4.666666666666667
3.8005847503304606
-4
10
5.0
