In this notebook we will discuss the following:
    
Reshape

Resize

ravel

flatten

ufunc

broadcast

indexing

In [1]:
import numpy as np

In [2]:
# ndim will return number of ndarray dimensions
a = np.arange(12)
print(a) 
print(a.ndim) #dimensions of the series, well dataframe

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1


In [3]:
b = np.array([[2, 5], [8, 11], [4, 17]])
print(b)
print(b.ndim)

[[ 2  5]
 [ 8 11]
 [ 4 17]]
2


In [4]:
# reshape() will reshape the array into the specified shape
a = np.arange(8)
b = a.reshape((2, 4)) # Change the array to size 2x4 #important concept
print(a)
print(b) 

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [5]:
c = a.resize((4,2))
print(c) 
# the above line will return None as resize modifies inplace Look this up, i have no clue what she is talking about
# while reshape creates a new array 
print(a)

None
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [6]:
flat_a = a.flatten()
print(flat_a)
# since flat_a is a new copy, any change to flat_a does not affect a

[0 1 2 3 4 5 6 7]


In [7]:
ravel_a = a.ravel() #shallow copy
print(ravel_a)
# ravel_a is not a copy, any change to ravel_a affects a 

[0 1 2 3 4 5 6 7]


In [8]:
ravel_a[0] = 10
print(ravel_a)
print(a)
# ravel_a is not a copy, any change to ravel_a affects a 

[10  1  2  3  4  5  6  7]
[[10  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]


In [9]:
# good time to talk about shallow copy vs deep copy

# shallow copy - points to the same location,
# Deep copy - creates new values in memory 
d = a
a[0][0] = -4
print(a)
print(d)
# note that d and a will have same values even though we modified only a

[[-4  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]
[[-4  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]


In [10]:
# Deep copy
e = a.copy() # e & a are different objects
a[0][0] = 3
print(a)
print(e)
# note that e and a will have different values

[[3 1]
 [2 3]
 [4 5]
 [6 7]]
[[-4  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]


In [11]:
"""
In-class activity - create an ndarray using arange that starts at 0 and stops 
at 12 in increments of 3. Then convert reshape the array to 2,2 then ravel the array. 
At each step, print the output.
"""
import numpy as np
# teacher: np.arrange(0, 12, step=3)

# p = np.linspace(start = 0, stop = 12, num = 4)
p = np.arange(0, 12, step=3)
print (p)
b = p.reshape(2,2)
print (b)
ravel_b = b.ravel()
p = np.linspace(start = -5, stop = 5, num = 10)
print (ravel_b)


[0 3 6 9]
[[0 3]
 [6 9]]
[0 3 6 9]


## List of ufuncs short for universal functions in numpy

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [12]:
# Universal functions are called ufunc 

a = np.arange(2, 6)
s = np.sin(a)
c = np.cos(a)
print(a)
print(s)
print(c)

[2 3 4 5]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[-0.41614684 -0.9899925  -0.65364362  0.28366219]


In [15]:
"""
In-class activity - for the above array "a" compute the inverse sine and cosine 
using arcsin and arccos.
"""

#she didn't test this, the problem is the numbers
new = [ 0.90929743  0.14112001 -0.7568025  -0.95892427]
# a = np.arange(, 6)
s = np.arcsin(new)
c = np.arccos(new)


SyntaxError: invalid syntax (<ipython-input-15-da47cecdd645>, line 5)

## Array Indexing

In [14]:
# Basic slicing
import numpy as np
a = np.random.rand(5, 5)*5
b = a.astype(np.int)
print(b)
print('The rows=1 and cols=2 element is {0}'.format(b[1,2])) 
print('The first col is {0}'.format(b[:,0])) # print all rows for cols=0 (column 0)  : means everything
print('The third row is {0}'.format(b[2, :])) # all cols for rows = 2

[[3 1 2 2 3]
 [0 4 0 0 2]
 [4 4 0 1 2]
 [0 2 3 0 0]
 [2 1 3 3 3]]
The rows=1 and cols=2 element is 0
The first col is [3 0 4 0 2]
The third row is [4 4 0 1 2]


In [15]:
# broadcasting - the process of supplying a value to 
# every element in an array

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array(-1)  #adds -1 to each value.  should use array as a priciple.  just a number will work but might jack up later
c = a + b
print(c)[ 0.90929743  0.14112001 -0.7568025  -0.95892427][ 0.90929743  0.14112001 -0.7568025  -0.95892427]

[[1 3 7]
 [2 4 6]
 [3 5 9]]


In [16]:
# Another example of broadcasting  
# used for imagery, example brightening an image, adding 30 to each cell


a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([1, 1, 1])
c = a + b
print(c)

[[ 3  5  9]
 [ 4  6  8]
 [ 5  7 11]]


In [17]:
# An example of sorting

a = np.array([[2, 5], [6, 4]])

print(np.sort(a)) # sort(a, axis, kind, order)
print("+++++++")
print(np.sort(a, order = None))
print("+++++++")
print(np.sort(a, axis = 0)) # along the column
print("+++++++")
print(np.sort(a, axis = 1)) # along the row

[[2 5]
 [4 6]]
+++++++
[[2 5]
 [4 6]]
+++++++
[[2 4]
 [6 5]]
+++++++
[[2 5]
 [4 6]]


In [18]:
 # we can also use sort() method to sort 
    
a.sort()
print(a) 

[[2 5]
 [4 6]]


In [24]:
"""
In-class activity - create an ndarray that is 2 by 3. Then broadcast value -5 to each element. 
Then sort the array first along the columns and then along the rows.
""" 

y = np.random.rand(2,3) * 20
bb = y.astype("int")
r = np.array(-5)
t = bb + r
print (y)
print (bb)
print (r)
print (t)
print("+++++++")
print(np.sort(t, axis = 0)) # along the column
print("+++++++")
print(np.sort(t, axis = 1)) # along the row

[[ 8.09955529 18.71935163  6.58774508]
 [19.81497339  0.73816802  5.17863914]]
[[ 8 18  6]
 [19  0  5]]
-5
[[ 3 13  1]
 [14 -5  0]]
+++++++
[[ 3 -5  0]
 [14 13  1]]
+++++++
[[ 1  3 13]
 [-5  0 14]]
