### In this notebook we will look at

random module

array manipulations

In [12]:
import numpy as np

In [13]:
# random.rand(x) will return an ndarray with x number of items that are 
# randomly selected between 0 and 1
a = np.random.rand(3)
print(a)

[0.03561705 0.25682229 0.39135311]


In [14]:
"""
using sort() to sort the elements in an ndarrray
sort(axis, kind)
all arguments are optional
axis can be specified, default -1 means sort along the last axis

kind can be quicksort, mergesort or heapsort. Default is quicksort
"""

a.sort() 
print(a)

[0.03561705 0.25682229 0.39135311]


In [15]:
# random.sample will return a random number from a uniform distribution from [0.0, 1.0) #every point has equal chance of being selected - that is what uniform distribution means
# 1.0 is not included
c = np.random.sample()
print(c)

0.8643896589961587


In [16]:
# random.choice(n) will return a number from an ndarray n
a = np.array([2, 6, 12, 18])
print(np.random.choice(a)) #picks from the specified array

6


In [17]:
"""
random.randint(x) will return an integer from the interval  [0, x], both are included
random.randint(x, y) will return an integer from [x, y]
random.randint(x, y, n) will return n integers between x and y
"""

print(np.random.randint(5))
print(np.random.randint(11, 15))
print(np.random.randint(-10, -5, 2))

1
13
[ -6 -10]


In [18]:
"""
In-class activity: 
From the list ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"] choose a name
"""
a = ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"]
print(np.random.choice(a))

Mike


In [19]:
"""
In-class activity:
Using random.rand create a 1D ndarray, then convert the values in the ndarray to integer 
and then choose a value from the new int adarray. At every step print the output. 

a = np.array([2.0,3,4])

"""
b = np.random.rand(24)*5 # do this to get the value past the 1 mark.  Called "broadcasting"
print (b)
c = b.astype("int")
print (c)
print (np.random.choice(c))




[1.18441478e+00 4.09379509e+00 3.96303488e+00 1.90581168e+00
 3.51074204e+00 4.54533870e+00 3.96318342e-01 1.75990657e+00
 1.16854755e-01 1.49083618e-01 1.75994945e+00 1.55233334e+00
 1.08847397e+00 2.77025202e+00 1.79032713e+00 2.63852299e+00
 1.76148592e+00 2.64580323e+00 5.81700064e-04 6.33800911e-01
 4.91601038e+00 4.64412682e+00 1.54894436e+00 1.39579872e+00]
[1 4 3 1 3 4 0 1 0 0 1 1 1 2 1 2 1 2 0 0 4 4 1 1]
4


#### Now we will look at the array manipulation

In [20]:
a = np.array([[2, 4], [7, 9]])
b = np.array([[1, 3], [6, 5]])

#  + * - / are element by element perations  1 to 1, the matrixes need to be the same  if not, they will be broadcasted

In [21]:
# using + operator we can compute element by element sum of two arrays
print(a + b)

[[ 3  7]
 [13 14]]


In [22]:
# using * operator we can compute element by element multiplication of two arrays

print(a * b) # element by element multiplication 

[[ 2 12]
 [42 45]]


In [23]:
# using - operator we can compute element by element subtraction of two arrays

print(a - b)

[[1 1]
 [1 4]]


In [24]:
# dot(a1, a2) will compute matrix multiplication

print(np.dot(a, b)) # matrix multiplication When dot is used.  What is matrix multiplication?  need to look this up.  there is a formula

[[26 26]
 [61 66]]


In [25]:
# @ can be used to perform matrix multiplication 
# @  is called the 'infix' operator and is only available in Python 3.5+ (PEP 465)

print(a @ b) 

[[26 26]
 [61 66]]


In [26]:
# if we have matrices then we can perfrom matrix multiplication using matmul(a1, a2)

print(np.matmul(a, b)) # matrix multiplication

[[26 26]
 [61 66]]


In [27]:
# in an array transpose() will interchange the rows to columns   ******* very important!! *********
# and vice-versa used to matrix multiply matrices that could not nomrally be multiplied  doesn't matter what you transpose, get the same value

print(np.transpose([[4, 7, 9], [5, 7, 10]]))

[[ 4  5]
 [ 7  7]
 [ 9 10]]


In [28]:
# T can also be used to transpose a matrix

y = np.array([[3, 5], [8, 11]])
print(y)
print(y.T)

[[ 3  5]
 [ 8 11]]
[[ 3  8]
 [ 5 11]]


In [39]:
"""

home work
In-class activity:
Create two 2-by-2 ndarrays. Compute the following:

1) Element by element multiplication

2) Array multiplication using two different methods
"""

x = np.array([[5,8], [7,2]])
y = np.array([[6,3], [1,9]])
print (x)
print(y)
print ('Element Multiplication: ' + str(x*y))
print ('Array Multiplication with @: ' + str(x@y))
print ('Array Multiplication with .dot: ' + str(np.dot(x, y)))

[[5 8]
 [7 2]]
[[6 3]
 [1 9]]
Element Multiplication: [[30 24]
 [ 7 18]]
Array Multiplication with @: [[38 87]
 [44 39]]
Array Multiplication with .dot: [[38 87]
 [44 39]]


In [43]:
"""
homework will be on quiz
n-class activity:
Create an 2-by-2 ndarray. Compute the following:

1) Transpose of the ndarray

2) array multiplication of the old array and the transposed array
"""

p = np.array([[5,8], [7,2]])
b = np.transpose(p)

print('Original: ' + str(p))
print('Transposed: ' + str(b))
print ('Multiplication of the array and the transposed array:' + str(a@b))


Original: [[5 8]
 [7 2]]
Transposed: [[5 7]
 [8 2]]
Multiplication of the array and the transposed array:[[ 42  22]
 [107  67]]
