### In this notebook we will look at

random module

array manipulations

In [3]:
import numpy as np

In [4]:
# random.rand(x) will return an ndarray with x number of items that are 
# randomly selected between 0 and 1
a = np.random.rand(3)
print(a)

[0.98741457 0.1882553  0.04854943]


In [5]:
"""
using sort() to sort the elements in an ndarrray
sort(axis, kind)
all arguments are optional
axis can be specified, default -1 means sort along the last axis

kind can be quicksort, mergesort or heapsort. Default is quicksort
"""

a.sort() 
print(a)

[0.04854943 0.1882553  0.98741457]


In [6]:
# random.sample will return a random number from a uniform distribution from [0.0, 1.0) #every point has equal chance of being selected - that is what uniform distribution means
# 1.0 is not included
c = np.random.sample()
print(c)

0.7773443053392047


In [7]:
# random.choice(n) will return a number from an ndarray n
a = np.array([2, 6, 12, 18])
print(np.random.choice(a)) #picks from the specified array

2


In [8]:
"""
random.randint(x) will return an integer from the interval  [0, x], both are included
random.randint(x, y) will return an integer from [x, y]
random.randint(x, y, n) will return n integers between x and y
"""

print(np.random.randint(5))
print(np.random.randint(11, 15))
print(np.random.randint(-10, -5, 2))

3
14
[-6 -7]


In [9]:
"""
In-class activity: 
From the list ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"] choose a name
"""
a = ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"]
print(np.random.choice(a))

Elizabeth


In [10]:
"""
In-class activity:
Using random.rand create a 1D ndarray, then convert the values in the ndarray to integer 
and then choose a value from the new int adarray. At every step print the output. 

a = np.array([2.0,3,4])

"""
b = np.random.rand(24)*5 # do this to get the value past the 1 mark.  Called "broadcasting"
print (b)
c = b.astype("int")
print (c)
print (np.random.choice(c))




[1.47218848 3.12370546 3.78747717 0.36229936 3.3031604  4.05547326
 4.20958537 3.5878888  3.77250073 2.44784941 3.75806149 4.16974401
 3.03963863 0.72810186 2.97482041 1.31367636 2.33967655 3.55531231
 0.49406477 1.08631631 1.4875495  0.68384945 4.51908375 0.34828627]
[1 3 3 0 3 4 4 3 3 2 3 4 3 0 2 1 2 3 0 1 1 0 4 0]
1


#### Now we will look at the array manipulation

In [11]:
a = np.array([[2, 4], [7, 9]])
b = np.array([[1, 3], [6, 5]])

#  + * - / are element by element perations  1 to 1, the matrixes need to be the same  if not, they will be broadcasted

In [10]:
# using + operator we can compute element by element sum of two arrays
print(a + b)

[[ 3  7]
 [13 14]]


In [11]:
# using * operator we can compute element by element multiplication of two arrays

print(a * b) # element by element multiplication 

[[ 2 12]
 [42 45]]


In [12]:
# using - operator we can compute element by element subtraction of two arrays

print(a - b)

[[1 1]
 [1 4]]


In [13]:
# dot(a1, a2) will compute matrix multiplication

print(np.dot(a, b)) # matrix multiplication When dot is used.  What is matrix multiplication?  need to look this up.  there is a formula

[[26 26]
 [61 66]]


In [14]:
# @ can be used to perform matrix multiplication 
# @  is called the 'infix' operator and is only available in Python 3.5+ (PEP 465)

print(a @ b) 

[[26 26]
 [61 66]]


In [15]:
# if we have matrices then we can perfrom matrix multiplication using matmul(a1, a2)

print(np.matmul(a, b)) # matrix multiplication

[[26 26]
 [61 66]]


In [16]:
# in an array transpose() will interchange the rows to columns   ******* very important!! *********
# and vice-versa used to matrix multiply matrices that could not nomrally be multiplied  doesn't matter what you transpose, get the same value

print(np.transpose([[4, 7, 9], [5, 7, 10]]))

[[ 4  5]
 [ 7  7]
 [ 9 10]]


In [17]:
# T can also be used to transpose a matrix

y = np.array([[3, 5], [8, 11]])
print(y)
print(y.T)

[[ 3  5]
 [ 8 11]]
[[ 3  8]
 [ 5 11]]


In [18]:
"""

home work
In-class activity:
Create two 2-by-2 ndarrays. Compute the following:

1) Element by element multiplication

2) Array multiplication using two different methods
"""

'\nIn-class activity:\nCreate two 2-by-2 ndarrays. Compute the following:\n\n1) Element by element multiplication\n\n2) Array multiplication using two different methods\n'

In [19]:
"""
homework will be on quiz
n-class activity:
Create an 2-by-2 ndarray. Compute the following:

1) Transpose of the ndarray

2) array multiplication of the old array and the transposed array
"""

'\nIn-class activity:\nCreate an 2-by-2 ndarray. Compute the following:\n\n1) Transpose of the ndarray\n\n2) array multiplication of the old array and the transposed array\n'